// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a configured asset — managed via frontend Settings UI.
 * Stored in RuntimeConfig → persisted in redb.
 * Config.toml [[asset_definitions]] serves as initial seed only.
 */
export type AssetMeta = { 
/**
 * Display symbol (e.g. "BTC")
 */
symbol: string, 
/**
 * Binance trading pair (e.g. "BTCUSDT") — used for RTDS subscription
 */
binance_symbol: string, 
/**
 * Lowercase keywords for market question matching (e.g. ["btc", "bitcoin"])
 */
keywords: Array<string>, };
