// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetMeta = { symbol: string, binance_symbol: string, keywords: Array<string>, };
