// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketKind = "UpDown" | "FiveMin" | "Above" | "Below" | "Dip" | "Reach" | "Range" | "Unknown";
