// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Registry entry for a known platform (used in status/config APIs).
 */
export type PlatformInfo = { name: string, url: string, authenticated: boolean, };
