// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Asset } from "./Asset";
import type { OrderStrategy } from "./OrderStrategy";

export type RuntimeConfig = { min_edge: string, min_prob: string, max_prob: string, max_spread: string, order_strategy: OrderStrategy, market_refresh_secs: number, assets: Array<Asset>, daily_loss_limit: string, daily_profit_cap: string, max_position_pct: string, max_concurrent: number, drawdown_limit: string, adverse_fill_pause: number, };
