// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single large trade observed from a whale wallet.
 */
export type WhaleActivity = { address: string, condition_id: string, side: string, amount: string, price: string, timestamp: string, question: string | null, platform: string, };
