// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Profile of a tracked whale wallet on any supported platform.
 */
export type WhaleProfile = { address: string, display_name: string | null, 
/**
 * Cumulative realized profit in USD
 */
profit: string, 
/**
 * Return on investment, e.g. 0.85 = 85%
 */
roi: number, 
/**
 * Win rate, e.g. 0.72 = 72%
 */
win_rate: number, 
/**
 * Total USDC volume traded
 */
volume: string, markets_traded: bigint, last_seen: string, 
/**
 * Whether we mirror this whale's signals in our strategy
 */
followed: boolean, };
