// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VenueId } from "./VenueId";

/**
 * One token balance line on a venue (collateral, native gas, outcome shares).
 */
export type TokenBalance = { venue: VenueId, token: string, amount: string, 
/**
 * USD-denominated value if the venue exposes a price oracle.
 */
usd_value: string | null, };
