// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a trading venue. Used as a key in maps and configs.
 */
export type VenueId = "polymarket" | "hyperliquid" | "kalshi";
