// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PositionInfo = { condition_id: string, side: string, size: string, entry_price: string, market: string, age_secs: number, };
