// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigSnapshot } from "./ConfigSnapshot";
import type { PositionInfo } from "./PositionInfo";
import type { PriceInfo } from "./PriceInfo";
import type { TradeInfo } from "./TradeInfo";

export type Tick = { daily_pnl: string, paused: boolean, heartbeat_alive: boolean, positions: number, orders: number, markets: number, signals: number, fills: number, adverse: number, reconnects: number, trades: Array<TradeInfo>, balance: string, win_rate: number, total_trades: number, orders_placed: number, orders_cancelled: number, mode: string, prices: { [key in string]: PriceInfo }, config: ConfigSnapshot, drawdown_pct: number, uptime_secs: number, open_positions: Array<PositionInfo>, };
