// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TradeInfo = { side: string, price: string, size: string, pnl: string | null, adverse: boolean, ts: string, market: string, };
